### PR TITLE
Update gradle.yml

### PR DESCRIPTION
**Pull request by adityasimant**
Solves #1157 

1. JDK Versions: The workflow is set up to test the code with multiple JDK versions (8, 11, 16, 17, 20). 
2. Caching: The workflow is configured to cache Gradle dependencies, which assumes that your Gradle build relies on caching for efficiency. If your project doesn't use Gradle or doesn't benefit from caching, you can remove the caching step.

### CODE REVIEW

**Comment by adityasimant** [comment]
Removed the matrix feature, back to using JDK version 20.

**Comment by mrbusche** [comment]
> Removed the matrix feature, back to using JDK version 20.

Why did you downgrade versions? Everything should stay on the latest version.

**Comment by adityasimant** [comment]
> > Removed the matrix feature, back to using JDK version 20.
> 
> Why did you downgrade versions? Everything should stay on the latest version.

Do you want me to use JDK 21?

**Comment by adityasimant** [comment]
Everything is updated to the latest version. The actions checkout version is v4.1.0, JDK is 20

**Comment by mrbusche** [comment]
Thanks! Looks good.

**Pull request merged**
